"""initial schema

Revision ID: ebb4955a971e
Revises: 
Create Date: 2026-05-18 21:24:40.886443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb4955a971e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('raw_metrics_json', sa.Text(), nullable=True),
    sa.Column('derived_metrics_json', sa.Text(), nullable=True),
    sa.Column('data_quality_flags_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('peak_flow', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('post_run_rpe', sa.Integer(), nullable=True),
    sa.Column('asthma_symptoms', sa.Integer(), nullable=True),
    sa.Column('saba_use', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runner_metrics_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vo2max', sa.Float(), nullable=True),
    sa.Column('vdot', sa.Float(), nullable=True),
    sa.Column('acwr', sa.Float(), nullable=True),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_history_session_id', 'conversation_history', ['session_id'])
    op.create_index('idx_health_log_date', 'health_log', ['date'])
    op.create_index('idx_runner_metrics_history_date', 'runner_metrics_history', ['date'])
    op.create_index('idx_audit_log_timestamp', 'audit_log', ['timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_log_timestamp', table_name='audit_log')
    op.drop_index('idx_runner_metrics_history_date', table_name='runner_metrics_history')
    op.drop_index('idx_health_log_date', table_name='health_log')
    op.drop_index('idx_conversation_history_session_id', table_name='conversation_history')
    op.drop_table('runner_metrics_history')
    op.drop_table('health_log')
    op.drop_table('runs')
    op.drop_table('conversation_history')
    op.drop_table('audit_log')
    # ### end Alembic commands ###